#ifndef CONFIG_SUJIKINEN_H
#define CONFIG_SUJIKINEN_H

#include "../../config.h"
#undef TAPPING_TERM
#define TAPPING_TERM 230
#define ONESHOT_TIMEOUT 2000
#define BACKLIGHT_BREATHING
#define FORCE_NKRO
#undef BACKLIGHT_LEVELS
#define BACKLIGHT_LEVELS 7

#endif
